name: Deploy
on:
  push:
  #   branches: main
  # pull_request:
  #   branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          tags: tag:signature

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            echo '${{ secrets.PASSWORD}}' | sudo -S chmod -R 777 /var/www 
            cd /var/www/example.org/ 
            cd Signature-Front-TS 
            git pull
            npm install
            npm run build
            mv dist/ signature/
            rm -rf ../signature/
            mv signature/ ..
